version: "3.4"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=abcdefghikjlm
    ports:
      - "27014:27017"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
